modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "superbwarfare"
version = "${mod_version}"
displayName = "Superb Warfare"
authors = "${mod_authors}"
logoFile = "logo.png"
description = "${mod_description}"

[[dependencies.superbwarfare]]
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"# Here's another dependency

[[dependencies.superbwarfare]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.superbwarfare]]
modId = "curios"
mandatory = true
versionRange = "[5.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.superbwarfare]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.superbwarfare]]
modId = "patchouli"
mandatory = false
versionRange = "[1.20.1-84,)"
ordering = "NONE"
side = "BOTH"
